name: GitHub Actions

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: ${{ matrix.task }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            task: unit-tests
    steps:
      - name: Prevent conversion of line endings on Windows
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: git config --global core.autocrlf false
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Use conda on Windows
        if: startsWith(matrix.os, 'windows')
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: false
      - name: Setup and run tests on Windows
        if: startsWith(matrix.os, 'windows')
        shell: sh
        run: |
          conda init powershell
          $env:GITHUB_WORKSPACE/.ci/test.sh
  # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
  all-successful:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: note that all tests succeeded
      run: echo "all tests succeeded"
